### ISSUE TITLE
Safer Date escaping

### ISSUE THREAD

**Issue by fabiospampinato** [WebReflection/sqlite-tag-spawned#3]
I don't know how important this is, but potentially this check is unsafe:

https://github.com/WebReflection/sqlite-tag-spawned/blob/d29a0247015361f91d398bff160372de439a7781/esm/utils.js#L28-L29

Something could be an instance of Date and overload the toISOString method to execute an arbitrary query.

**Comment by WebReflection** [comment]
This is backend code … even string replace could be overloaded, or array iterator, so I’m not sure what you’re after 🤔

it’s either 100% defensive code or trust your dependencies? I mean … I work in this space https://javascript.plainenglish.io/about-trusting-javascript-execution-8c6b478d6021

**Comment by fabiospampinato** [comment]
Yeah I guess if you can't trust your own dependencies all bets are off already anyway. I just spotted that when going through the code, I thought I'd mention it.

**Comment by WebReflection** [comment]
it's not different from `[].join('')` after an `Array.isArray(thing)` ... or any `object.hasOwnProperty(thing)` or whatever `toString()` operation, including *Buffer* instances ... basically the reason [proxy-pants](https://github.com/WebReflection/proxy-pants#readme) exists and we use it to secure our code against malicious software, but here we're on the server, and I don't see why I should care about that in particular and nothing else.
