### ISSUE TITLE
Automatic Uint8Array to Hex conversion 

### ISSUE THREAD

**Issue by fabiospampinato** [WebReflection/sqlite-tag-spawned#4]
It'd be nice if the Blob data type were kind of transparently supported by converting Uint8Arrays into `x'[hex-content-here]'`.

**Comment by fabiospampinato** [comment]
Though that could be a little problematic since the mode is set to JSON by default, those bytes will probably balloon in size once converted to JSON.

**Comment by WebReflection** [comment]
cool idea that might work as INSERT/UPDATE but like you stated, not sure what's going to happen once retrieved as JSON ... will have a look and see if there's any way to have those "blobs" back.

**Comment by fabiospampinato** [comment]
They just get converted to JSON strings, with all the control characters expressed as unicode escape sequences.

**Comment by WebReflection** [comment]
well ... then it looks like a utility to convert back might work as solution?

**Comment by fabiospampinato** [comment]
Yeah, sure. I guess depending on the use case that may be better than base64-encoding the thing. I guess the pro is that that would consume less memory/disk, but I don't quite like that a buffer goes in and a string comes out, and I don't know if sending bigger strings back and fort from sqlite would meaningfully slow down things. I'm not sure also what the performance of encoding/decoding hex is compared to encoding/decoding base64. I suppose on average it's a worthwhile extra thing to support though.

**Comment by WebReflection** [comment]
all encoding are done natively but if you have strong need of blobs then I suggest *not* using this module, as it's obviously not ideal for that scenario ... this is more for streaming JSON directly to a piped response or work with data and leave files and blobs outside SQLite (which is also usually suggested in general) as you can't really search, or relate, much with SQL and blobs, isn't it? So this is not really a use case I'd put effort to support, as it looks like the wrong tool for the job, but I wouldn't mind having a tiny helper to retrieve back the blob, if that works ... still I don't have much time these days!

**Comment by fabiospampinato** [comment]
Yeah, it wouldn't be ideal for that. My use case is kind of weird, I'm still figuring things out, files and their metadata would be encrypted on the server so I just need some place to store them, keeping everything in a sqlite database seems just more convenient than having a million files all over the place, and it's probably more reliable and faster too. I could potentially skip the encoding/decoding but it seems just more convenient to put base64-encoded things in the database 🤔

**Comment by WebReflection** [comment]
> keeping everything in a sqlite database seems just more convenient than having a million files all over the place

you can create a non compressed archive if *one file* is what you are after ... SQLite with tons of blobs would give you headaches with *VACUUM* ... I mean, it's an RDB, blobs have no relations beside a pointer (the file path) but hey, you do what you want to do, just saying I think trashing blobs in any DB is *not* ideal, like ... ever, imho.

**Comment by fabiospampinato** [comment]
I'll see how it goes, putting blobs in SQLite or putting them in some kind of archive should be kind of the same really, except that I trust SQLite more, I'd need to use SQLite for other things anyway so better to keep using one set of tools for everything in this case, and there are actually some very simple queries that I need to execute on those tables that will be mostly full of blobs, however simple those queries might be SQLite should be more suitable for them.

**Comment by WebReflection** [comment]
ok ... so, considering there's nothing I can do around the fact JSON produces what it produces (I haven't tried to switch binary though but I don't think it does what I think it does), and considering JSON mode is here to stay, how would like to solve this? 🤔

**Comment by WebReflection** [comment]
how to pass `x'...'` is not the real issue, it's more about how you'd like to have it back ... would a utility work? ... such as `x(returned_string)` ???

**Comment by fabiospampinato** [comment]
I don't have a decent solution for that unfortunately 🤔

**Comment by WebReflection** [comment]
there is a native function though, example:

```sh
SELECT id, hex(data) AS data FROM test;
```

this avoid ugly JSON escape all over the place and requires `btoa` to get back the buffer (or any hex to buffer converter)

**Comment by fabiospampinato** [comment]
That's not bad 🤔 Lower disk usage by using Blobs, no JSON encoding which we don't really even want, hex encoding done in C-land presumably with great performance... nice.

**Comment by WebReflection** [comment]
yup ... so ... beside accepting blobs, it looks like there's nothing to do on the returning side (or better, the utility is not really needed) ... right?

**Comment by fabiospampinato** [comment]
It looks like it, yeah.

**Comment by WebReflection** [comment]
done 👍
