### ISSUE TITLE
Support for exporting/serializing/deserializing

### ISSUE THREAD

**Issue by fabiospampinato** [WebReflection/sqlite-tag-spawned#5]
It'd be nice if the following got implemented:

- Support for backing up a database into a separate file, something like `sqlite3 foo.db ".backup 'foo.db.bak'"` interally.
- Support for serializing a database to a Uint8Array, which is like a backup but the file is read and deleted afterwards.
- Support for deserializing a serialized database, which is kinda like `:memory:` but the buffer is written in the temp file.

**Comment by WebReflection** [comment]
> Support for backing up a database into a separate file

an sqlite3 db backup is a copy ... an fs.copyFile, not a SQL command, unless you want the export as .csv or something else, but you have the sqlite3 CLI for that, no need for this module?

> Support for serializing a database to a Uint8Array, which is like a backup but the file is read and deleted afterwards.

not clear ... the db as blob is already usable as Uint8Array and even sqlite on the client. what is that you need here?

> Support for deserializing a serialized database, which is kinda like :memory: but the buffer is written in the temp file.

not clear again ... maybe writing down use cases would help ... but it looks more and more you are not interested in this module use case, as you are asking too much blobs stuff around ... may I suggest again *not* to use this project, if blobs is all you care about?

**Comment by WebReflection** [comment]
> Actually that's not how it works

OK, if you have different journal, fair enough, so let me give you a solution:

```sh
sqlite3 file.db '.backup file.bck'
```

that's it? you can do that either via the exported `query` or directly via CLI ... then you can grab that as blob and read it as whatever typed array you like.

**Comment by fabiospampinato** [comment]
Yeah that's basically it really, or I least I implemented it that way, potentially it could be interesting to stop the module from making mutating queries to the database while a backup is in progress or something, I don't know enough of how the backup process works in practice to know if that would help though.

**Comment by WebReflection** [comment]
> potentially it could be interesting to stop the module from making mutating queries to the database

every sqlite3 can connect in the meanwhile, and so would do clusters when the DB is the same ... I don't think better-sqlite or any other can really guarantee that, but AFAIK the backup will execute after any commit happens, or rollback, so I am not sure what issue we are trying to solve here, if plain standard SQLite is the answer ;-)
