### ISSUE TITLE
Queries with empty arrays are broken

### ISSUE THREAD

**Issue by mirnovov** [WebReflection/sqlite-tag-spawned#7]
The array interpolation feature usually works great, but when given an empty array, it fails.

```js
const a = new SQLiteTag(':memory:', { readonly: true, persistent: true });
const b = await a.all`SELECT * FROM (VALUES (1), (2)) WHERE column1 NOT IN (${[-1]})`;
console.log(b);
```
correctly returns `[ { column1: 1 }, { column1: 2 } ]` but
```js
const a = new SQLiteTag(':memory:', { readonly: true, persistent: true });
const b = await a.all`SELECT * FROM (VALUES (1), (2)) WHERE column1 NOT IN (${[]})`;
console.log(b);
```
either produces an error or returns nothing.

This is because your dependency `static-params` doesn't return a value for empty arrays when converting JS format strings to SQL parameters. Your code in [utils.js](https://github.com/WebReflection/sqlite-tag-spawned/blob/main/esm/utils.js) assumes that the amount of statement fragments is always `v+1`, where `v` is the amount of substituted values. But since the SQL statement is still split at an empty array but no value is provided, this assumption is incorrect.

A possible solution would be to specifically account for empty arrays by returning a value of `''`, as I [have done](https://github.com/mirnovov/obsidian-importer/blob/7cd498f15608e4d6d088489116faa439b05f1c6e/src/formats/apple-notes/sqlite/static-params.js#L16) in my project that bundles `sqlite-tag-spawned`. I'm unsure if this would break other things that rely on `static-params` though.

**Comment by WebReflection** [comment]
to clarify, with template literal tags the template is always v+1 length as defined by specs ... please read again the README and the examples, in no circumstances you pass a complex object as interpolation.

**Comment by mirnovov** [comment]
```sql
SELECT * FROM (VALUES (1), (2)) WHERE column1 NOT IN (-1)
```

```sql
SELECT * FROM (VALUES (1), (2)) WHERE column1 NOT IN ()
```
I don't know if all SQL engines support using VALUES like this but SQLite does. But the same occurs when using more normal syntax:

```
const l = [-1];

const a = new SQLiteTag(':memory:', { readonly: true, persistent: true });
await a.query`CREATE TABLE test (first INTEGER, second INTEGER)`;
await a.query`INSERT INTO test (first, second) VALUES (1, 1), (2, 2)`;

const b = await a.all`SELECT first FROM test WHERE first NOT IN (${l})`;
console.log(b);
```

**Comment by mirnovov** [comment]
https://www.sqlite.org/lang_expr.html#booleanexpr

> Note that SQLite allows the parenthesized list of scalar values on the right-hand side of an IN or NOT IN operator to be an empty list but most other SQL database engines and the SQL92 standard require the list to contain at least one element.

**Comment by WebReflection** [comment]
I think I want that to work in here too ... why not filing a PR? 😄

**Comment by mirnovov** [comment]
I've opened one in your `static-params` repo since that's where the query parameters are parsed; it'd be hard to include a fix in this repo given how you've designed things.

**Comment by WebReflection** [comment]
sure and ... thanks! I'll do the update dance right after that gets merged

**Comment by mirnovov** [comment]
Thanks!
