### ISSUE TITLE
Is query amnesic?

### ISSUE THREAD

**Issue by thipages** [WebReflection/sqlite-tag-spawned#8]
Hi,

I try to import a csv file with the following code (it works when manually written in the console)
```javascript
  import SQLiteTagSpawned from 'sqlite-tag-spawned'
  const {query} = SQLiteTagSpawned(dbPath)
  await query`.mode csv`
  await query`.separator ;`
  await query`.import "./myFile.csv" myTable`
```
I got the following : `Error: SQLITE_ERROR: ./myFile.csv:1: expected 42 columns but found 1 - filling the rest with NULL`
The apparent reason is that the separator is not the one I tried to set but the default one
I tried to add `{ persistent: true }` option, got other errors

The minimum example I found (without the need of importing csv) follows :

```javascript
  import SQLiteTagSpawned from 'sqlite-tag-spawned'
  const {query} = SQLiteTagSpawned(':memory')
  await query`.mode csv`
  console.log(await query`.show`)
```
The corresponding output shows that .mode csv command has been forgotten (`mode: list`)
```
echo: off
eqp: off
explain: auto
headers: off
mode: list
nullvalue: ""
output: stdout
colseparator: "|"
rowseparator: "\n"
stats: off
width:
filename: [full temp path]
```
Where am I wrong?
Thank you.

**Comment by WebReflection** [comment]
From the [README](https://github.com/WebReflection/sqlite-tag-spawned/blob/main/README.md#differently-from-dblite):

> each query is a spawn call except for transactions, grouped as single spawned query


this would also completely break if you drop the mode JSON so I suggest you use dblite instead

**Comment by WebReflection** [comment]
P.S. you can use a transaction instead which executes all commands at once so for the initial db import that might be it

**Comment by thipages** [comment]
Hi,
I try to use transactions below) but got  `Error: SQLITE_ERROR: Error: in prepare, near`
Will try dblite
Thank you.

```javascript
    const {transaction } = SQLiteTagSpawned(':memory:')
    const populate = transaction()
    populate`.mode csv`
    populate`.show`
    await populate.commit()
```
